# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, vNext]
    paths:
      - '**'
      - '!src/**'
      - '!live-editing/configs/**'
      - 'live-editing/configs/app-dv-configs/**'
      - '!live-editing/generators/**'
      - 'live-editing/generators/AppDVConfigGenerators.ts'
      - '!projects/app-crm/**'
  pull_request:
    branches: [ master, vNext]
    paths:
      - '**'
      - '!src/**'
      - '!live-editing/configs/**'
      - 'live-editing/configs/app-dv-configs/**'
      - '!live-editing/generators/**'
      - 'live-editing/generators/AppDVConfigGenerators.ts'
      - '!projects/app-crm/**'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: 'Generate live editing and build samples'
        run: npm run build:app-lob
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
